version: 2
jobs:
  build:
    macos:
      xcode: "9.0"

    steps:
      - checkout
      - run:
          name: Install rpm
          command: brew install rpm
      - run:
          name: Build and run tests
          command: yarn && yarn test && yarn package
      - store_artifacts:
          path: release

  docker-dependencies:
    docker:
      - image: dataworld/pyenv-tox

    working_directory: /root/knot

    environment:
      SALESFORCE_VERSION: "1.4.14"
      STITCH_VERSION: "1.7.4"
      MYSQL_VERSION: "1.9.10"
      POSTGRES_VERSION: "0.0.16"
      ADWORDS_VERSION: "1.3.3"
      FACEBOOK_VERSION: "1.5.1"
      S3_CSV_VERSION: "0.0.3"

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker build
          working_directory: /root/knot/docker/images
          command: |
            docker build --build-arg version=$SALESFORCE_VERSION -t dataworld/tap-salesforce -t dataworld/tap-salesforce:$SALESFORCE_VERSION ./tap-salesforce
            docker build --build-arg version=$STITCH_VERSION -t dataworld/target-stitch -t dataworld/target-stitch:$STITCH_VERSION ./target-stitch
            docker build --build-arg version=$MYSQL_VERSION -t dataworld/tap-mysql -t dataworld/tap-mysql:$MYSQL_VERSION ./tap-mysql
            docker build --build-arg version=$POSTGRES_VERSION -t dataworld/tap-postgres -t dataworld/tap-postgres:$POSTGRES_VERSION ./tap-postgres
            docker build --build-arg version=$ADWORDS_VERSION -t dataworld/tap-adwords -t dataworld/tap-adwords:$ADWORDS_VERSION ./tap-adwords
            docker build --build-arg version=$FACEBOOK_VERSION -t dataworld/tap-facebook -t dataworld/tap-facebook:$FACEBOOK_VERSION ./tap-facebook
            docker build --build-arg version=$S3_CSV_VERSION -t dataworld/tap-s3-csv -t dataworld/tap-s3-csv:$S3_CSV_VERSION ./tap-s3-csv
      - deploy:
          name: docker-hub release
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dataworld/tap-salesforce:latest
            docker push dataworld/tap-salesforce:$SALESFORCE_VERSION
            docker push dataworld/target-stitch:latest
            docker push dataworld/target-stitch:$STITCH_VERSION
            docker push dataworld/tap-mysql:latest
            docker push dataworld/tap-mysql:$MYSQL_VERSION
            docker push dataworld/tap-postgres:latest
            docker push dataworld/tap-postgres:$POSTGRES_VERSION
            docker push dataworld/tap-adwords:latest
            docker push dataworld/tap-adwords:$ADWORDS_VERSION
            docker push dataworld/tap-facebook:latest
            docker push dataworld/tap-facebook:$FACEBOOK_VERSION
            docker push dataworld/tap-s3-csv:latest
            docker push dataworld/tap-s3-csv:$S3_CSV_VERSION

workflows:
  version: 2
  app:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - docker-release
  dependencies:
    jobs:
      - docker-dependencies:
          filters:
            branches:
              only:
                - docker-release
